-- Question 1

-- PART A 

SELECT SUM(INVOICE_TOTAL) FROM INVOICES

-- PART B

SELECT ROUND(AVG(INVOICE_TOTAL),3) FROM INVOICES

-- PART C

SELECT COUNT(DISTINCT VENDOR_ID) FROM INVOICES

-- PART D

SELECT ROUND(STDDEV(INVOICE_TOTAL),3) FROM INVOICES

-- Question 2

SELECT e.EMPLOYEE_ID, e.LAST_NAME, e.FIRST_NAME, j.PROJECT_NUMBER
FROM EMPLOYEES  e
JOIN PROJECTS  j on e.EMPLOYEE_ID = j.EMPLOYEE_ID
ORDER BY j.PROJECT_NUMBER DESC;

-- Question 3

SELECT VENDOR_ID, INVOICE_NUMBER,INVOICE_DUE_DATE,PAYMENT_DATE 
FROM INVOICES
WHERE PAYMENT_DATE IS NOT NULL;

-- Question 4
SELECT DISTINCT VENDOR_ID FROM VENDORS
MINUS
SELECT DISTINCT VENDOR_ID FROM INVOICES;

--The result of this query will be a list of VENDOR_ID values from the VENDORS table that do not exist in the INVOICES table.

-- Question 5
SELECT * FROM ORDER_ITEMS
WHERE ITEM_PRICE > (SELECT AVG(LIST_PRICE) FROM PRODUCTS)





